### ISSUE TITLE
create a button for light mode and dark mode, the dark mode style must keep the current

### ISSUE THREAD

**Issue by JoselaineRibas** [JoselaineRibas/receipt-calculator#8]
A header can be created yesterday if it contains the title and in the left corner the button to change the mode

**Comment by georgioupanayiotis** [comment]
please assign me this @JoselaineRibas

**Comment by georgioupanayiotis** [comment]
created the PR [here](https://github.com/JoselaineRibas/receipt-calculator/pull/9)
